version: '3'

services:
  php:
    build:
      context: '.'
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html/
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
#      - 127.0.0.1:3306:3306
#      - 172.17.0.1:3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_USER=docker
      - MYSQL_DATABASE=docker
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
